apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "doc-search-chart.fullname" . }}
  labels:
    {{- include "doc-search-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "doc-search-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "doc-search-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12}}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12}}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12}}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
